### ISSUE TITLE
It works but dosent autoplay

### ISSUE THREAD

**Issue by GamebP** [lanylow/quaver-autoplay#2]
@lanylow

**Comment by Jamie-PROG** [comment]
needs sig update

**Comment by lanylow** [comment]
Should be fixed now.

**Comment by GamebP** [comment]
WOW ! I'll test it out

**Comment by GamebP** [comment]
I'm 1.5k in 7k lol. 
Best auto program I have ever used

Edit: Got IP banned from the game, website, even playing simple 0.4* maps...

**Comment by lanylow** [comment]
> Edit: Got IP banned from the game, website, even playing simple 0.4* maps...

I wonder why

**Comment by GamebP** [comment]
Atleast I had my fun

**Comment by lanylow** [comment]
Yeah, you probably also got hardware banned because Quaver collects some basic hardware information.

**Comment by GamebP** [comment]
Software? I wouldnt think so..

**Comment by GamebP** [comment]
They ip ban you from the game. Nothing much. Atleast I made it to #1 link
to banned profile
https://web.archive.org/web/20240804021508/https://quavergame.com/user/705456?mode=1

lanylow ***@***.***> (šajā datumā: svētd., 2024. g. 4. aug.
02:12) rakstīja:

**Comment by lanylow** [comment]
> They ip ban you from the game. Nothing much.

I'm sure they have code to collect some serial numbers, I don't know whether they use it for bans.

> Atleast I made it to #1 link to banned profile https://web.archive.org/web/20240804021508/https://quavergame.com/user/705456?mode=1

The graph looks funny
